# Basic Information 
title: Kun Yan
position: Ph.D.
# department: School of Telecommunications Engineering
affiliation: Xidian University
affiliation_link: https://www.xidian.edu.cn/
affiliation_logo: ./assets/img/xidian.svg #./assets/img/university-logo-small-horizontal-white-156eae9527.svg
location: Xi'an, China
email: kyan@stu.xidian.edu.cn

# Search Engine Optimization (SEO)
keywords: kun yan, yan kun, kunyan, yankun, quin yim, yim quin, quinyim, yimquin
canonical: https://quinyim.github.io/
description: Kun Yan received his Ph.D. degree from the School of Telecommunications Engineering, Xidian University. His research interests include 6G networks, blockchain, and Internet of things.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true


# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=NyUwUmIAAAAJ
# orcid: https://orcid.org/0000-0002-3619-8966
#researchgate: https://www.researchgate.net/profile/Kun-Yan-24
linkedin: https://www.linkedin.com/in/kun-yan-744040323/
# clarivate: https://webofscience.clarivate.cn/wos/author/record/HLX-1711-2023
# scopus: https://www.scopus.com/authid/detail.uri?authorId=58088423400
#twitter: https://twitter.com/
cv_link: ./assets/files/Kun_Yan_CV.pdf
github_link: https://github.com/QuinYim

# Images 
avatar: ./assets/img/kun.png
favicon: ./assets/img/favicon-dark.png
favicon_dark: ./assets/img/favicon-dark.png

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# The option is used to show the last update time.
enable_last_update: true

# Footnotes
footnote: Kun Yan © 2024 - 2025
# footnote_link: https://quinyim.github.io/

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME