# Basic Information 
title: Kun Yan / Quin Yim
position: Ph.D. Student
affiliation: Xidian University
#affiliation_link: https://cs.jhu.edu/
affiliation_logo: ./assets/img/xidian3.png #./assets/img/university-logo-small-horizontal-white-156eae9527.svg
location: Xi'an, China
email: kyan@stu.xidian.edu.cn

# Search Engine Optimization (SEO)
keywords: kun yan, yan kun, kunyan, yankun, quin yim, yim quin, quinyim, yimquin
canonical: https://quinyim.github.io/
description: Kun Yan is a Ph.D. student at School of Telecommunications Engineering, Xidian University. His research interests include 6G networks, blockchain, and Internet of things.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: true

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=NyUwUmIAAAAJ
orcid: https://orcid.org/0000-0002-3619-8966
researchgate: https://www.researchgate.net/profile/Kun-Yan-24
#twitter: https://twitter.com/Wen_Zhong_
#cv_link: https://drive.google.com/file/d/1_kWjcUHizGGheXU5_wYcaHc0IKuhtiqT/view?usp=sharing
github_link: https://github.com/QuinYim
#linkedin: https://www.linkedin.com/in/wen-zhong-9a59771a5/

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon-dark.png
favicon_dark: ./assets/img/favicon-dark.png

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Footnotes
# footnote: Quin Yim.
# footnote_link: https://quinyim.github.io/

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
#clustrmaps_id: 

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
